### ISSUE TITLE
Bundle an implicit conversion from Query to QueryExpression

### ISSUE THREAD

**Issue by aa-dit-yuh** [MscrmTools/MscrmTools.FluentQueryExpressions#12]
Allows passing the `Query` directly to `IOrganizationService` without having to access the `QueryExpression` member. See https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/user-defined-conversion-operators

Helps here:

```csharp
query = new Query("entityname");
_service.RetrieveMultipleAsync(query.QueryExpression); // before
_service.RetrieveMultipleAsync(query); // after
```

**Comment by aa-dit-yuh** [comment]
Please merge #13 if you agree with this addition.

**Comment by MscrmTools** [comment]
Great one! 
I'm really not a super developer as I did not know implicit operators!
I do agree
