### ISSUE TITLE
How is this library different from Microsoft.Xrm.Sdk.Client.OrganizationServiceContext.CreateQuery?

### ISSUE THREAD

**Issue by siggipop** [MscrmTools/MscrmTools.FluentQueryExpressions#8]
label: question
How is this library different from Microsoft.Xrm.Sdk.Client.OrganizationServiceContext.CreateQuery<TEntity>?

**Comment by MscrmTools** [comment]
Good question :) 

This library is made to be fully discoverable (all condition operators are translated in methods for example) but less verbose than traditionnal QueryExpression.

So I would say this library can help you find everything you can do when querying Dataverse. LINQ in the other hand lets you write anything you want but you are not sure a valid query expression will be generated for Dataverse.
