### ISSUE TITLE
2.0.1 Release for v8 package

### ISSUE THREAD

**Issue by kschepperly** [MscrmTools/MscrmTools.FluentQueryExpressions#9]
I am currently working in Dynamics 365 CE v8.2 (On-Premise) and therefore am using MscrmTools.FluentQueryExpressions.**v8**.

I noticed that v8 is still at v1.5 and was wondering if you have plans to release v2.0.1 for v8. I would be interested in leveraging the lambdas, specifically in the WhereEquals methods.

**Comment by MscrmTools** [comment]
That is possible! Will do it this week

**Comment by MscrmTools** [comment]
It's released
